version: '3'

services:
  test:
    build: .
    image: card-transform
    volumes:
      - "./:/source:rw"
    working_dir: /source
    command: >
      bash -c "/usr/bin/env NODE_PATH=/usr/local/lib/node_modules npm install ava &&
               /usr/bin/env NODE_PATH=/usr/local/lib/node_modules npm test"
